### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [Siipis/kustantajat#3]
# Katselmointi

Terve @Siipis! Tässä lyhyt katselmointi Full Stack kurssin projektistasi.

### Mitä tein?

- Selasin kustantamoja eri hakukriteereillä ja tutkin visualisaatioita
- Kirjauduin sisään hallintapneeliin
- Selasin kustantamojen profiileja, kirjoja, avainsanoja ja kategorioita

### Kokemus

- Tyylikäs ja helppokäyttöinen käyttöliittymä sekä hallintapneelissa, että kustantamohaussa. Kustantamohaun fontti- ja värivalinnat sopivat hyvin sovellukseen. Hyvää työtä! 🏆
- Erinomaiset visualisaatiot. Avainsanojen sanapilvi kertoo paljon kustantamosta ja pikaisella vilkaisulla
- Olisi kätevää, jos kustantamohaussa selaimen osoiterivin polku vaihtuisi kun hakukriteerit muuttuvat, tai kun kustantamon ikkuna avataan. Tämän avulla käyttäjä pystyisi jakamaan hakutulokset, tai kustantamon visualisaatiot linkillä
- Voiko hallintapaneelista kirjautua ulos?

## Koodi

- Frontend-puolen koodi on selkeästi organisoitua, hyvä!
- [Inline-tyylejä](https://github.com/Siipis/kustantajat/blob/master/src/App.js#L49), eli tyylien määrittelemistä `style` propsin avulla kannattaa välttää. Määrittele tyylit sen sijaan omissa tyylitiedostoissa (CSS tai SASS) ja käytä sopivia valitsimia, esim. luokkia ja `className` propsia. [Css-moduuleilla](https://github.com/css-modules/css-modules) tyylien määrittelemisestä tulee modulaarista, eikä valitsimien yhteentörmäyksistä tarvitse murehtia
- [Tässä](https://github.com/Siipis/kustantajat/blob/master/src/App.js#L27) on hyvä käyttökohde [Array.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)-metodille
- Monta yhtäaikaista `dispatch`-kutsua voi "batchata" käyttämällä [batch](https://react-redux.js.org/api/batch#batch)-funktiota. Tällöin React-komponenteissa tapahtuu vain yksi uudellen-renderöinti `dispatch`-kutsun seurauksena sen sijaan, että jokainen kutsu aiheuttaisi uudelleen-renderöinnin. Tämän kaltainen, monimutkaisempi logiikka, kannataisi eristää nk. [thunk](https://github.com/reduxjs/redux-thunk)-actioniin
- Funktionaaliset-komponentit ja [hook API](https://reactjs.org/docs/hooks-reference.html) ovat tutustumisen arvoisia
- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!

## Kokonaisuus

- Erittäin hyödyllinen sovellus, jossa tyylikässä ja käyttäjäystävällinen käyttöliittymä. Toiminallisuus on hiottua, eikä käytössä ilmennyt virhetilanteita, tai erityisiä käytettävyysongelmia
- Koodi on kaikin puolin hyvin organisoitua ja sen sisäinen laatu on pääosin korkea. Pidin pääpainon katselmoinnissa frontend-toteutuksen puolella, mutta myös backend-toteutus vaikutti nopealla vilkaisulla erittäin hyvältä

**Comment by Siipis** [comment]
Kiitos paljon palautteesta! <3
